//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatPhong()
        {
            this.ChiTietDonDatPhongs = new HashSet<ChiTietDonDatPhong>();
        }
    
        public int MaDonDatPhong { get; set; }
        public Nullable<System.DateTime> NgayDatPhong { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgaySuLy { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatPhong> ChiTietDonDatPhongs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
